// Generated by wxt
export {}
declare global {
  const ContentScriptContext: typeof import('wxt/utils/content-script-context')['ContentScriptContext']
  const DAISANGEN: typeof import('/Users/kenta/repo/MahjongSoul-review-supporter/utils/mahjongDataParser')['DAISANGEN']
  const DAISUUSHI: typeof import('/Users/kenta/repo/MahjongSoul-review-supporter/utils/mahjongDataParser')['DAISUUSHI']
  const DRAGS: typeof import('/Users/kenta/repo/MahjongSoul-review-supporter/utils/mahjongDataParser')['DRAGS']
  const ENNAME: typeof import('/Users/kenta/repo/MahjongSoul-review-supporter/utils/mahjongDataParser')['ENNAME']
  const InvalidMatchPattern: typeof import('wxt/utils/match-patterns')['InvalidMatchPattern']
  const JPNAME: typeof import('/Users/kenta/repo/MahjongSoul-review-supporter/utils/mahjongDataParser')['JPNAME']
  const Kyoku: typeof import('/Users/kenta/repo/MahjongSoul-review-supporter/utils/mahjongDataParser')['Kyoku']
  const MatchPattern: typeof import('wxt/utils/match-patterns')['MatchPattern']
  const NAMEPREF: typeof import('/Users/kenta/repo/MahjongSoul-review-supporter/utils/mahjongDataParser')['NAMEPREF']
  const POINTS: typeof import('/Users/kenta/repo/MahjongSoul-review-supporter/utils/dataConversion')['POINTS']
  const PRETTY: typeof import('/Users/kenta/repo/MahjongSoul-review-supporter/utils/mahjongDataParser')['PRETTY']
  const RONAME: typeof import('/Users/kenta/repo/MahjongSoul-review-supporter/utils/mahjongDataParser')['RONAME']
  const RUNES: typeof import('/Users/kenta/repo/MahjongSoul-review-supporter/utils/mahjongDataParser')['RUNES']
  const SHOWFU: typeof import('/Users/kenta/repo/MahjongSoul-review-supporter/utils/mahjongDataParser')['SHOWFU']
  const TSUMOGIRI: typeof import('/Users/kenta/repo/MahjongSoul-review-supporter/utils/mahjongDataParser')['TSUMOGIRI']
  const VERBOSELOG: typeof import('/Users/kenta/repo/MahjongSoul-review-supporter/utils/mahjongDataParser')['VERBOSELOG']
  const WINDS: typeof import('/Users/kenta/repo/MahjongSoul-review-supporter/utils/mahjongDataParser')['WINDS']
  const browser: typeof import('wxt/browser')['browser']
  const createIframeUi: typeof import('wxt/utils/content-script-ui/iframe')['createIframeUi']
  const createIntegratedUi: typeof import('wxt/utils/content-script-ui/integrated')['createIntegratedUi']
  const createShadowRootUi: typeof import('wxt/utils/content-script-ui/shadow-root')['createShadowRootUi']
  const deaka: typeof import('/Users/kenta/repo/MahjongSoul-review-supporter/utils/mahjongDataParser')['deaka']
  const deepCopy: typeof import('/Users/kenta/repo/MahjongSoul-review-supporter/utils/dataConversion')['deepCopy']
  const defineAppConfig: typeof import('wxt/utils/define-app-config')['defineAppConfig']
  const defineBackground: typeof import('wxt/utils/define-background')['defineBackground']
  const defineContentScript: typeof import('wxt/utils/define-content-script')['defineContentScript']
  const defineUnlistedScript: typeof import('wxt/utils/define-unlisted-script')['defineUnlistedScript']
  const defineWxtPlugin: typeof import('wxt/utils/define-wxt-plugin')['defineWxtPlugin']
  const download: typeof import('/Users/kenta/repo/MahjongSoul-review-supporter/utils/mahjongDataParser')['download']
  const extractTable: typeof import('/Users/kenta/repo/MahjongSoul-review-supporter/utils/dataConversion')['extractTable']
  const fakeBrowser: typeof import('wxt/testing')['fakeBrowser']
  const generatelog: typeof import('/Users/kenta/repo/MahjongSoul-review-supporter/utils/mahjongDataParser')['generatelog']
  const getPlayerDan: typeof import('/Users/kenta/repo/MahjongSoul-review-supporter/utils/mahjongDataParser')['getPlayerDan']
  const getPlayerRate: typeof import('/Users/kenta/repo/MahjongSoul-review-supporter/utils/mahjongDataParser')['getPlayerRate']
  const getPlayerSex: typeof import('/Users/kenta/repo/MahjongSoul-review-supporter/utils/mahjongDataParser')['getPlayerSex']
  const getRuleDisplay: typeof import('/Users/kenta/repo/MahjongSoul-review-supporter/utils/mahjongDataParser')['getRuleDisplay']
  const injectScript: typeof import('wxt/utils/inject-script')['injectScript']
  const makeaka: typeof import('/Users/kenta/repo/MahjongSoul-review-supporter/utils/mahjongDataParser')['makeaka']
  const pad_right: typeof import('/Users/kenta/repo/MahjongSoul-review-supporter/utils/mahjongDataParser')['pad_right']
  const parsehule: typeof import('/Users/kenta/repo/MahjongSoul-review-supporter/utils/mahjongDataParser')['parsehule']
  const relativeseating: typeof import('/Users/kenta/repo/MahjongSoul-review-supporter/utils/mahjongDataParser')['relativeseating']
  const soul2naga: typeof import('/Users/kenta/repo/MahjongSoul-review-supporter/utils/dataConversion')['soul2naga']
  const storage: typeof import('wxt/utils/storage')['storage']
  const tlround: typeof import('/Users/kenta/repo/MahjongSoul-review-supporter/utils/mahjongDataParser')['tlround']
  const tm2t: typeof import('/Users/kenta/repo/MahjongSoul-review-supporter/utils/mahjongDataParser')['tm2t']
  const toNagaHand: typeof import('/Users/kenta/repo/MahjongSoul-review-supporter/utils/dataConversion')['toNagaHand']
  const toNagaLog: typeof import('/Users/kenta/repo/MahjongSoul-review-supporter/utils/dataConversion')['toNagaLog']
  const toSoulTable: typeof import('/Users/kenta/repo/MahjongSoul-review-supporter/utils/dataConversion')['toSoulTable']
  const useAppConfig: typeof import('wxt/utils/app-config')['useAppConfig']
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Browser } from 'wxt/browser'
  import('wxt/browser')
  // @ts-ignore
  export type { StorageArea, WxtStorage, WxtStorageItem, StorageItemKey, StorageAreaChanges, MigrationError } from 'wxt/utils/storage'
  import('wxt/utils/storage')
  // @ts-ignore
  export type { WxtWindowEventMap } from 'wxt/utils/content-script-context'
  import('wxt/utils/content-script-context')
  // @ts-ignore
  export type { IframeContentScriptUi, IframeContentScriptUiOptions } from 'wxt/utils/content-script-ui/iframe'
  import('wxt/utils/content-script-ui/iframe')
  // @ts-ignore
  export type { IntegratedContentScriptUi, IntegratedContentScriptUiOptions } from 'wxt/utils/content-script-ui/integrated'
  import('wxt/utils/content-script-ui/integrated')
  // @ts-ignore
  export type { ShadowRootContentScriptUi, ShadowRootContentScriptUiOptions } from 'wxt/utils/content-script-ui/shadow-root'
  import('wxt/utils/content-script-ui/shadow-root')
  // @ts-ignore
  export type { ContentScriptUi, ContentScriptUiOptions, ContentScriptOverlayAlignment, ContentScriptAppendMode, ContentScriptInlinePositioningOptions, ContentScriptOverlayPositioningOptions, ContentScriptModalPositioningOptions, ContentScriptPositioningOptions, ContentScriptAnchoredOptions, AutoMountOptions, StopAutoMount, AutoMount } from 'wxt/utils/content-script-ui/types'
  import('wxt/utils/content-script-ui/types')
  // @ts-ignore
  export type { WxtAppConfig } from 'wxt/utils/define-app-config'
  import('wxt/utils/define-app-config')
  // @ts-ignore
  export type { ScriptPublicPath, InjectScriptOptions } from 'wxt/utils/inject-script'
  import('wxt/utils/inject-script')
}
