// Generated by wxt
import "wxt/browser";

declare module "wxt/browser" {
  export type PublicPath =
    | ""
    | "/"
    | "/_locales/en/detailed-description.txt"
    | "/_locales/en/messages.json"
    | "/_locales/ja/detailed-description.txt"
    | "/_locales/ja/messages.json"
    | "/_locales/zh_CN/detailed-description.txt"
    | "/_locales/zh_CN/messages.json"
    | "/_locales/zh_TW/detailed-description.txt"
    | "/_locales/zh_TW/messages.json"
    | "/background.js"
    | "/content-scripts/majsoul.js"
    | "/content-scripts/mjai.js"
    | "/content-scripts/naga.js"
    | "/imgs/Animation.gif"
    | "/imgs/extension_icon128.png"
    | "/imgs/extension_icon48.png"
    | "/index.css"
    | "/mahjongDataParser.js"
    | "/options.html"
    | "/popup.html"
  type HtmlPublicPath = Extract<PublicPath, `${string}.html`>
  export interface WxtRuntime {
    getURL(path: PublicPath): string;
    getURL(path: `${HtmlPublicPath}${string}`): string;
  }
}
